import { Router } from "express";
import { authRouter } from "./auth/auth.routes.js";
import { usersRouter } from "./users/users.routes.js";
import { rolesRouter } from "./roles/roles.routes.js";
import { permissionsRouter } from "./permissions/permissions.routes.js";
import { privilegesRouter } from "./privileges/privileges.routes.js";
import { departmentsRouter } from "./departments/departments.routes.js";
import { categoriesRouter } from "./categories/categories.routes.js";
import { ticketsRouter } from "./tickets/tickets.routes.js";
import { assetsRouter } from "./assets/assets.routes.js";
import { maintenanceRouter } from "./maintenance/maintenance.routes.js";
import { inventoryRouter } from "./inventory/inventory.routes.js";
import { incidentsRouter } from "./incidents/incidents.routes.js";
import { slaRouter } from "./sla/sla.routes.js";
import { automationRouter } from "./automation/automation.routes.js";
import { notificationsRouter } from "./notifications/notifications.routes.js";
import { analyticsRouter } from "./analytics/analytics.routes.js";
import { reportsRouter } from "./reports/reports.routes.js";
import { knowledgeBaseRouter } from "./knowledge-base/knowledge-base.routes.js";
import { auditRouter } from "./audit/audit.routes.js";
import { settingsRouter } from "./settings/settings.routes.js";

export const apiRouter = Router();

apiRouter.use("/auth", authRouter);
apiRouter.use("/users", usersRouter);
apiRouter.use("/roles", rolesRouter);
apiRouter.use("/permissions", permissionsRouter);
apiRouter.use("/privileges", privilegesRouter);
apiRouter.use("/departments", departmentsRouter);
apiRouter.use("/categories", categoriesRouter);
apiRouter.use("/tickets", ticketsRouter);
apiRouter.use("/assets", assetsRouter);
apiRouter.use("/maintenance", maintenanceRouter);
apiRouter.use("/inventory", inventoryRouter);
apiRouter.use("/incidents", incidentsRouter);
apiRouter.use("/sla", slaRouter);
apiRouter.use("/automation", automationRouter);
apiRouter.use("/notifications", notificationsRouter);
apiRouter.use("/analytics", analyticsRouter);
apiRouter.use("/reports", reportsRouter);
apiRouter.use("/knowledge-base", knowledgeBaseRouter);
apiRouter.use("/audit", auditRouter);
apiRouter.use("/settings", settingsRouter);
